### ISSUE TITLE
Add support to filter by relationships

### ISSUE THREAD

**Issue by chanjsq** [spatie/laravel-query-builder#101]
Say filter resource A by specify its related resource B's conditions.

**Comment by AlexVanderbist** [comment]
I would merge a tested PR that adds this. 

#124 is a pretty good first attempt - however it only works for filters with one level of nesting (e.g. `?filter[address.street_name]` but not `?filter[address.country.name]`).

For anyone needing this now: you can easily accomplish the same behaviour using a [scope filter](https://github.com/spatie/laravel-query-builder#scope-filters) or custom filter.

For example using a scope filter:
```php
// in your model
public function streetNameLike($query, $value) {
    return $query->whereHas('address', function ($q) use ($value) {
        return $q->where('street_name', 'LIKE', "%{$value}%")
    });
}
```

```php
QueryBuilder::for(User::class)->allowedFilters([
    Filter::scope('street_name_like'),
])
```

**Comment by SamDevBR** [comment]
@AlexVanderbist  actually I was successful using this package in lumen without the fork, I just had to create two helpers (request, config_path) and publish the service provider and the config file, maybe remove these helper dependicies and create functions to do same would be great, the only thing left to do to use this with Lumen would be create the vendor:publish command, because lumen doesn't have it.

**Comment by UnnitMetaliya** [comment]
seems like filtering on multiple level nesting is possible now. 

Just tried something like: `filter[referralsPromoCode.coupon.type]` and it worked fine.
