### ISSUE TITLE
QueryBuilder not working correctly 

### ISSUE THREAD

**Issue by braulioholtz** [spatie/laravel-query-builder#107]
I need to select only a few columns from my table, follow the code.

``
return QueryBuilder::for(Ingest::select('id', 'video_id', 'status'))->allowedSorts(['id'])->defaultSort('-id')->jsonPaginate();
``

When I do this, it returns with all the columns and not the three that I specified (Ingest :: select ('id', 'video_id', 'status')) ... is there any way to default to display some columns I to define?

**Comment by hulkur** [comment]
as it is built you have to specify fields in query and use `allowedFields()` https://github.com/spatie/laravel-query-builder#selecting-specific-columns

but there is a bug in the code: if you specify `allowedFields` but give no fields in query then you get `map() on null` error in `guardAgainstUnknownFields()`

Question to maintainers: 
Should allowedFields be applied even if no fields are specified in query? 
Check and give error that user needs to specify fields in query?

**Comment by AlexVanderbist** [comment]
Hi @braulioholtz, I've added an extra test for your issue here: c91648f. However I can't seem to replicate your issue. Can you confirm you're still experiencing this issue on the latest version?

@hulkur I can confirm that `map() on null` error. Thanks for reporting this - I'll tag a bugfix in a couple of minutes. 

For the default behaviour: `allowedFields` without selecting any fields in the query shouldn't modify the base query at all. E.g. `QueryBuilding::for(User::class)->allowedFields('name')->get()` should still return all fields. If you'd want to limit the query to a set of field I'd suggest using `QueryBuilder::for(User::select('name', 'id'))`.

This way you can also do the opposite: provide a tiny response by default but allow the consumer of the endpoint to fetch more information as they please: 
E.g.: `QueryBuilder::for(Post::select('id', 'title'))->allowedFields('id', 'title', 'big_html_content')` allows the consumer to `GET /posts` a basic list of posts but also `GET `/posts?fields=id,name,big_html_content` with the big payload included.

**Comment by AlexVanderbist** [comment]
That `map() on null` error was fixed in 08cf95d6778343ac29358ba6e18a1d5817911dff - gonna close this for now.
