### ISSUE TITLE
Filter on nested models?

### ISSUE THREAD

**Issue by Nowi5** [spatie/laravel-query-builder#168]
Hi,

I hope you are doing find. Just as a question and not a bug:
**How does a filter for a nested model look like?**

E.g. a City belongs to a Country. Of course I can filter['name']=Berlin on the City, but how would I be able to filter on the Country = Germany? The City Table just have a column country_id.
![grafik](https://user-images.githubusercontent.com/27913135/52259502-e6a85680-295d-11e9-9ead-e87f28ff6859.png)

How would the GET request look like and what do I need in the controller?
```
$cities = QueryBuilder::for(City::class)
            ->allowedFilters('name', 'country')
            ->allowedIncludes('language', 'currency')
            ->paginate();
```

Thank you very much!

**Comment by dominikb** [comment]
Take a look at [RelationFilterTest](https://github.com/spatie/laravel-query-builder/blob/master/tests/RelationFilterTest.php) to see examples on how to query for properties on a relation.

In order to use this, you need to define a [relation](https://laravel.com/docs/5.7/eloquent-relationships) on your `City` model.

```php
public function country(): BelongsTo
{
    return $this->belongsTo(Country::class);
}
```

Then you can allow to filter for the name of the country the city belongs to.

```php
// /cities?filter[country.name]=Deutschland
QueryBuilder::for(City::class)
    ->allowedFilters('country.name')
    ->allowedIncludes('language', 'currency')
    ->paginate();
```

**Comment by farshadff** [comment]
can this be done for sorting too ?? i mean sorting by related fields
