### ISSUE TITLE
When defaultSort is set, any sort aliasing doesn't work

### ISSUE THREAD

**Issue by Rezrazi** [spatie/laravel-query-builder#217]
**Environment**

| Type | Version |
| ------------- | ------------- |
| Laravel  | 5.8.3 |
| PHP  | 7.2 |
| MySQL | 5.7 |
| Package version | 1.16.0 |

**Issue**
Having a `defaultSort()` set, when trying to add aliasing with `Sort::field()`, it throws an error : 
```sql
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'joined' in 'order clause' (SQL: select * from `users` order by `joined` asc)
```

**Steps to reproduce**
1. Install package, no configuration change
2. 
```php
$users = QueryBuilder::for(User::class)
   ->defaultSort('name')
   ->allowedSorts(Sort::field('joined', 'created_at'))
   ->get();
```
3. Request
`/users?sort=joined`

***Note***
It works without a default sort
```php
$users = QueryBuilder::for(User::class)
   ->allowedSorts(Sort::field('joined', 'created_at'))
   ->get();
```

**Comment by VinceG** [comment]
Having the same issue.

**Comment by dominikb** [comment]
In short, the problem lies within sorts being parsed multiple times.

By default, all sort clauses are allowed and when adding a default sort before allowing a specific sort, it adds the `order by joined asc` part to the query.
When trying to add the allowed sort with the given alias afterward, it gets filtered out as a duplicate condition.

PR #215 solves this issue, as well as the issue of clauses being added multiple times, by aiming to only parse sorts once.
I will update the PR to add a test for this scenario and get it ready for a merge.

**Comment by francoism90** [comment]
Confirm the same issue, any update on possible merge/fix? :)

**Comment by leeovery** [comment]
Seeing same
