### ISSUE TITLE
why deprecate Laravel 5.5 support

### ISSUE THREAD

**Issue by Yangwendaxia** [spatie/laravel-query-builder#230]
For the sake of safety and stability, the latest Laravel LTS version will be the first priority in business production . I think it is unwise to depriciate Laravel 5.5 support , it also means a potential risk for those developers who have applied this package in project with Laravel 5.5 already.  Is there any unavoidable reason ?

**Comment by springjk** [comment]
>Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY include minor and patch level changes. Patch and minor version
https://semver.org/ 

Deprecate lTS version is not a good idea, and you should change the X version even if you want to do this, now user use it  must lock the version to `1.16.0`,  this does not respect SemVer.

**Comment by freekmurze** [comment]
We don't use L5.5 anymore, so it makes no sense for us to invest time in this anymore. I don't really care about LTS. If you're stuck on an older version of Laravel use an older version of the package.

Removing support for an older version of a dependency is not a breaking change because the public API was not changed.

**Comment by mavichow** [comment]
I've similar problem due to the reason we're using `v1.13.1` on October CMS with laravel/framework of `v5.5.44`, previously we installed successfully, but right now we couldn't install `v1.13.1` to laravel/framework of `v5.5.44` we're hitting error. Possible allow it to install on older versions?
