### ISSUE TITLE
Custom sort fails in combination with scope filter

### ISSUE THREAD

**Issue by arjanwestdorp** [spatie/laravel-query-builder#309]
The custom sort fails when it's used in combination with two scope filters. Not sure if it's really related to the scope filters, but when using exact filters instead it's giving the expected output at least.

Instead of calling the custom sort class the property is used as name to filter on. Somewhere the custom sort seems to be converted to a `SortsField`.

When placing the `allowedSorts` before the `allowedFilters` everything works as expected. It seems that it's related to #165 .

```
/** @test */
public function it_fails()
{
    $sortClass = new class implements SortInterface {
        public function __invoke(Builder $query, $descending, string $property) : Builder
        {
            return $query->orderBy('name', $descending ? 'desc' : 'asc');
        }
    };

    $sortedModels = QueryBuilder::for(TestModel::class, new Request([
        'filter' => [
            'name' => 'foo',
            'between' => '2016-01-01,2017-01-01',
        ],
        'sort' => '-custom'
    ]))
        ->allowedFilters([
            Filter::scope('name', 'named'),
            Filter::scope('between', 'createdBetween'),
        ])
        ->allowedSorts([
            Sort::custom('custom', get_class($sortClass))
        ])
        ->defaultSort('foo')
        ->get();

    $this->assertQueryExecuted('select * from "test_models" where "name" = ? and "created_at" between ? and ? order by "name" desc');
    $this->assertSortedAscending($sortedModels, 'name');
}
```

It's sorting on `order by "custom" desc` instead

**Comment by AlexVanderbist** [comment]
Hi, something definitely seems off here. However, I've added the same test on the v2 branch of the package that'll be tagged later this week and it seems to be fixed there due to some internal changes/cleanup. So I'm not gonna fix this for now (as you said, you can change the order of `allowedSorts` and `allowedFilters` to work around this). Thanks for reporting this and feel free to open a PR if you really want to see this fixed in v1 :)
