### ISSUE TITLE
Custom Sorting by Nested Relationship .

### ISSUE THREAD

**Issue by farshadff** [spatie/laravel-query-builder#354]
i am writing a custom relation to sort my model by its relationship but the problem is that i want to sort my models by the relations of that relation whic means the nested relationship .
so if i have this now :
```
            ->allowedSorts([AllowedSort::custom('hits', new PriceSort(),'hits'),

```
and in my `PriceSort`
```
 $direction = $descending ? 'DESC' : 'ASC';
        return $query->with('accommodationRooms.roomPricingHistorySearch')
        ->orderByRaw("(`{$property}`) {$direction}");
```
here now i want to sort the `$query` which is my hotel Model by one of the `roomPricingHistorySearch` fields . how can i achive that ??

**Comment by AlexVanderbist** [comment]
It's difficult to do this with Eloquent out of the box as its relations will be loaded in multiple queries. 

I'd advice you to add a `JOIN` clause to the query that `SELECT`s the relevant `roomPricingHistorySearch`. You can then order by the joined value. So basically skipping the relationship entirely. 

If you need help with this or have any other questions, feel free to open a new issue (closing this one because it's been idle for 2 months). Thanks!
