### ISSUE TITLE
Filter and sorting allowedAppends on model 

### ISSUE THREAD

**Issue by farshadff** [spatie/laravel-query-builder#359]
hi i have a accessor that i am using the allow append to append that to my model using this package . now i want to know if i can perform some sorting or filtering on that too because when i filter or sort it in normal way it gives the column not found error here is my code below :
```
  ->allowedAppends(['cheapestroom'])
            ->allowedIncludes(['gallery','city','accommodationRooms','accommodationRooms.roomPricingHistorySearch','discounts'])
            ->allowedSorts([
                AllowedSort::custom('discount', new DiscountSort() ,'amount'),
                'discounts.amount'
            ])
            ->allowedFilters([
            AllowedFilter::scope('bed_count'),
            AllowedFilter::scope('filter_price'),
            AllowedFilter::exact('grade_stars'),
            AllowedFilter::exact('city_id'),
            AllowedFilter::exact('is_recommended'),
            AllowedFilter::exact('accommodation_type_id'),
            'name','discounts.amount'
            ])
            ->paginate(10);
```

**Comment by AlexVanderbist** [comment]
Hi! I'm guessing you've since figured this out as the issue is 2 months old (sorry). 

Either way, this is due to the fact that this package only manipulates Eloquent queries before they're executed. Appends are, as the name suggests, appended after execution. So appends are added after filtering/sorting/including has already happened. 

I'd suggest creating a `cheapestroom` relationship and using that instead of the appended attribute. Good luck!
