### ISSUE TITLE
allowedFields() doesn't make sense

### ISSUE THREAD

**Issue by Trixpua** [spatie/laravel-query-builder#361]
What is the purpose for allowedFields()?

Once that if fields['table'] is not specified in the request the default behaviour is select all fields. But if I want select only some fields, this need to be explicitly defined as allowed field.

I think this approach don't have any bennefits, only headaches, because if I want allow to select some fields instead all of them I need explicitly define all my table fields and all relations fields, otherwise it throw and error.

In version 1.* the behavior make more sense, by default select all fields and if specified a fields['table'] in request select only this fields.

I don't know if is possible, but a better approach can be a protectFields() method, that remove from Colletion the defined fields.

**Comment by klimov-paul** [comment]
Unfortunally, Laravel does not provide any way to get all model's attributes (e.g. all DB table columns).
Such functionality can be achieved using [doctrine/dbal](https://packagist.org/packages/doctrine/dbal).

Also list of model attributes can be collected combining `Model::getFillable()` and `Model::getGuarded()`, but this way may be unreliable.

**Comment by Trixpua** [comment]
But I still don't understand why have an allowedFields() method, if even I declared some fields as allowed, but the API user don't select this fields with a fields['table'] argument in the request the default behavior is return all fields.

I think that this is unnecessary once default behavior is send return all fields, if keep the behavior like in version 1.* make much more sense.

-> By default select all fields.
-> if specified a fields['table'] in request select only this fields

The problem with the version 2.* behavior is that for example I have a table products that have a lot of relations (e.g. category, orders, ...) and I want to allow that user select only necessary fields for him, let's say for example (for product table => id, name, category_id and for category table => category_id, name) I will need to explicit specify this fields as allowed using allowedFields() method, but later the user will need and extra field for product table, let's say "price" and this is not defined so will thrown an error.

So if the user needs a field that is not allowed will need send the request without a fields['table'] argument in the request and receive all fields by default to get access to this field.

I believe that the purpose of select is to reduce the size of fields returned and the currently approach don't allow to do it in a efficient way.

**Comment by klimov-paul** [comment]
> The problem with the version 2.* behavior

I am sorry, but I can not see any significant difference between 2.x and 1.x versions behavior regardless `allowedFields()` methods:

- [1.17.5](https://github.com/spatie/laravel-query-
builder/blob/1.17.5/src/Concerns/AddsFieldsToQuery.php)
- [2.3.0](https://github.com/spatie/laravel-query-builder/blob/2.3.0/src/Concerns/AddsFieldsToQuery.php)

Perhaps I miss something.

> I don't know if is possible, but a better approach can be a protectFields() method, that remove from Colletion the defined fields.

This is not going to work well, because there is no way of finding **all** table fields in Laravel.
If you allow API client to specify any field for selection, only excluding some predefined list, it will cause inconsistent behavior.

For example assume we have following code with `protectFields()` feature:

```php
QueryBuilder::for(Item::class)
    ->protectFields([
         'price', // allow: 'id', 'name'
    ])
   // ...
```

In case API client sends following request:

```
{
   "fields": {"items": "unexisting_field"}
}
```

It will trigger a database query exception: "no such column 'unexisting_field' in table 'items'", and API client will receive 500 "Internal Server Error" response.
I am unsure whether API client will be able to exploit and SQL injection here or not.
Still, sending back 500 error is not appropriate - it should be 4xx error instead.

**Comment by klimov-paul** [comment]
As for "sense": `allowedFields()` method should be used in junction with `select()` method, allowing to expand originally limited list of fields. For example:

```php
QueryBuilder::for(Item::query()->select('id', 'name')) //default select
    ->allowedFields('id', 'name', 'description', 'price') // maximum allowed select
```

Here only 'id' and 'name' columns will be returned by default, while API client may in addition explicitly select 'description' and 'price' if necessary.

**Comment by AlexVanderbist** [comment]
Hi, I'm afraid @klimov-paul is right. Having **all** fields allowed by default worked by not having any constraints on the input query. However, this was indeed vulnerable to sql injections and the aforementioned 500 error. We could catch the exception but that doesn't fix the SQLi issue.

I agree that the developer experience was a bit better before, but we we were exposing people to some serious security issues.

As for solutions: you could use doctrine/dbal to set all fields as `allowedFields()` by default. You could even add your `protectedFields()` method by creating your own `QueryBuilder` class that extends ours but implements the `protectedFields` method using doctrine/dbal. 

Good luck!

**Comment by mblarsen** [comment]
> As for "sense": `allowedFields()` method should be used in junction with `select()` method, allowing to expand originally limited list of fields. For example:

Hi @klimov-paul and @AlexVanderbist could you give an example how this would work with relations. 

For one model it works fine. You set a limited default `select(id, name, uuid)` and then the user can "override" this from the list of `allowedFields(id, name, uuid, job_id)`.

So for relations I do like this:

```php
        // AssignmentQuery.php
        parent::__construct(Assignment::query()->select([
            'id', 
            'phase',
            'job_id',
            'job.id',    // <--- will be ignored in case 2
            'job.uuid',    // <--- will be ignored in case 2
            'job.title',    // <--- will be ignored in case 2
        ]));
```
(and way longer allowed lists)

Case 0: No job works:

```
?fields[assignments]=id,job_id&fields[job]=id,uuid,title&include=job
```
(this works despite the job.* selects)

Case 1: This case works just fine:

```
?fields[assignments]=id,job_id&fields[job]=id,uuid,title&include=job
```

Case 2: However if I exclude the middle (job) part:

```diff
- ?fields[assignments]=id,job_id&fields[job]=id,uuid,title&include=job
+ ?fields[assignments]=id,job_id&include=job
```
The entire job, beyond what is allowed is returned for job. This is really unexpected.

Ideally the select should only be overwritten for the relevant includes. 

- Am I missing something?
- I could help out, but I'm not sure if this is at all possible. Since the allowed-methods changes the query as the functions are invoked there isn't much to do later just before querying is there or can one  override `get` and then "adjust" the select based on what received in the request?

**Comment by zenepay** [comment]
```php
        $query = QueryBuilder::for(
            Employee::class
            // $query->where(static::getKeyName(), $id)
        )->allowedFields(['id', 'first_name'])
            ->toSql();
```
      The result is Select * from employees
      It won't just selects id and first_name as expected. So, it won't work.
