### ISSUE TITLE
how to sort by a relationship attribute 

### ISSUE THREAD

**Issue by farshadff** [spatie/laravel-query-builder#362]
Its not a bug or and Issue its more a question for me . i am aware of making custom sort class but when i use join on that it destroys data on other models and it returns null for fields of id and relationships i have no idea why !!! can i use the old dot for the relation of sort like this in the test : 
```
  ->allowedSorts([
                'related_model.property'
            ])```
for sorting like up above ? or if not what is the best way of doing that

**Comment by AlexVanderbist** [comment]
Sadly sorting by related properties using the dot-notation is not possible. This is a limitation in eloquent. There's some info on this issue here: https://github.com/spatie/laravel-query-builder/issues/36

So that's why we added custom sorts in the first place. Using a join in the custom sort should do the trick. However, you gotta make sure not to overwrite any joined tables or select any required fields for Eloquent relationships you might want to include. You can do this using aliases in the SELECT and JOIN clauses you're adding for sorting. 

Finally, this package doesn't add any magic to Eloquent. If you're really stuck I'd suggest trying to create a working Eloquent query first before turning it into a Query Builder query. Just to make sure the query is actually possible. Good luck and feel free to open a new issue if you still need help with this!

**Comment by anthonymf** [comment]
> Sadly sorting by related properties using the dot-notation is not possible. This is a limitation in eloquent. 

By adding an explicit select and a join, dot-notation becomes possible, see https://github.com/spatie/laravel-query-builder/issues/36#issuecomment-1100911854
