### ISSUE TITLE
How to sort on a column from Relationship

### ISSUE THREAD

**Issue by seewhy17** [spatie/laravel-query-builder#413]
I have a Loan Model that is related to Account and User Models. I am trying to sort by lastname which come from the account relation but neither 
```
        $loans = Loan::with(['account', 'user']);
        $loans = QueryBuilder::for($loans)
                ->allowedSorts(['lastname', 'amount'])
                ->get();
```

 NOR 

```
        $loans = Loan::with(['account', 'user']);
        $loans = QueryBuilder::for($loans)
                 ->allowedIncludes(['account', 'user'])
                ->allowedSorts(['lastname', 'amount'])
                ->get();
```
Worked

**Sorry I don't know how to tag this as a question, I know its not really an Issue, Thanks**

**Comment by dominikb** [comment]
Take a look at the test that covers this feature:

https://github.com/spatie/laravel-query-builder/blob/d0d82095138f961241c81efe0a40147009ad6d4d/tests/SortTest.php#L91-L104

**Comment by JanMisker** [comment]
Thanks for your great open source projects!
I am looking for this feature, so ended up in this (closed) question (and a few others).

This SQL 
```sql
select * from `test_models` order by `related_models`.`name` asc
````
is obviously not valid SQL, there should be a `JOIN`.
My impression is that this will never work, because how I understand it Eloquent loads the related table rows in a second query.

**Comment by JanMisker** [comment]
Ah nevermind I found this issue with more comments: https://github.com/spatie/laravel-query-builder/issues/36
