### ISSUE TITLE
Loading relationships and attributes for a specific model

### ISSUE THREAD

**Issue by Davidnadejdin** [spatie/laravel-query-builder#445]
Often when creating an api, I don’t always know when certain relationships or attributes may be needed. What if you do something similar to what is used to get a collection of models?

As far as I understand now, I can do it something like this:
```
public function show(Category $category)
    {
        $category = QueryBuilder::for(Category::class)->allowedIncludes([
            // relations
        ])->allowedAppends([
            // attributes
        ])->find($category->id);
    }
```

What if to make it possible to exclude an additional request from `find`, For example, at least like this:
```
public function show(Category $category)
    {
        $category = QueryBuilder::for($category)->allowedIncludes([
            // relations
        ])->allowedAppends([
            // attributes
        ]);
    }
```
or so:
```
public function show(Category $category)
    {
        $category->allowIncludes([
            // relations
        ])->allowedAppends([
            // appends
        ]);

    }
```

**Comment by AlexVanderbist** [comment]
I'll accept a PR to make `QueryBuilder::for()` accept a model, like `$category` and have it create a query builder instance for the `Category` model and have it automatically add `whereKey($category->id)`.

However, reducing the number of requests is not gonna be possible as we can't load relationships on a `Model` the same way we load relationships on a `QueryBuilder`. We could change the whole package to use some kind of interface that would call `$model->load('relationship')` instead of `$builder->with('relationship')` but that's a bit out of scope for this package :)

Personally I use your first example, but you're right, that will perform at least one additional request.

**Comment by Davidnadejdin** [comment]
> I'll accept a PR to make `QueryBuilder::for()` accept a model, like `$category` and have it create a query builder instance for the `Category` model and have it automatically add `whereKey($category->id)`.
> 
> However, reducing the number of requests is not gonna be possible as we can't load relationships on a `Model` the same way we load relationships on a `QueryBuilder`. We could change the whole package to use some kind of interface that would call `$model->load('relationship')` instead of `$builder->with('relationship')` but that's a bit out of scope for this package :)
> 
> Personally I use your first example, but you're right, that will perform at least one additional request.

maybe not worth it? Once the functionality is beyond the scope of the package.

I did about what I wanted:
https://github.com/envant/laravel-model-mutator

**Comment by AlexVanderbist** [comment]
Alright, glad you got it sorted!
