### ISSUE TITLE
Limiting fields when no field is specified in URL 

### ISSUE THREAD

**Issue by ablishek** [spatie/laravel-query-builder#457]
Whilst building a query, I can select the fields I would like an API to provide. And this works perfectly when an API calls out those specific fields. But when no fields are assigned in the url, all fields are shown, even those fields that weren't part of the allowedFields list. This can cause issues with hidden data that I may not want to publicly show.

```
        return QueryBuilder::for(User::class)
            ->allowedFields(
                'handle',
                'name',
                 ...
                 )
```

Is there any way, I can restrict only these fields to show if no fields are mentioned in the url? @AlexVanderbist

**Comment by zabavnikov** [comment]
Same problem.

**Comment by ondast** [comment]
Same problem. Also for related models.

**Comment by renanBritz** [comment]
"allowedFields" is not working at all. WTF?

**Comment by AlexVanderbist** [comment]
Hi! This not including all allowed fields by default is actually by design. The Query Builder will only modify the underlying query if it's requested to do so. So without a request for specific fields, we wont add any selects. They're also allowed fields and not default fields :) 

The easy way you could fix this is by adding your own `select()` with a set of default fields. Maybe store them in a separate variable to use the same array for both the default `select` and the `allowedFields` call.

```php
$publicFields = ['id', 'name', 'email'];
QueryBuilder::for(User::class)
     ->select($publicFields)
     ->allowedFields($publicFields);
// You can now select any subset of the $publicFields by adding them to the fields query parameter
```

Good luck!

**Comment by killjin** [comment]
How to limit fields of optional relational table?
