### ISSUE TITLE
AllowedFiliter callback throws an error

### ISSUE THREAD

**Issue by cosecantt** [spatie/laravel-query-builder#458]
Laravel 6.15.1

Filter url:
````/search?q=test&filter[country_code]=US&filter[rating]=3````

The following

````
use Spatie\QueryBuilder\QueryBuilder;
use Illuminate\Database\Query\Builder;
use Spatie\QueryBuilder\AllowedFilter;

$products = QueryBuilder::for(Product::class)
    ->allowedFilters([
         'country_code', 
         AllowedFilter::callback('rating', function (Builder $query, $value) {
              $query->where('rating', '>=', $value);
         }),
    ])->get();
````

throws error

````
Argument 1 passed to App\Http\Controllers\Home\SearchController::App\Http\Controllers\Home\{closure}() must be an instance of Illuminate\Database\Query\Builder, instance of Spatie\QueryBuilder\QueryBuilder given
````

But when I remove typehint ````Builder```` as:
````
... function($query, $value){
...
})...
````
it does not throw any error works as expected.

**Comment by AlexVanderbist** [comment]
Hey, you'll want to import the `Builder` typehint as `Illuminate\Database\Eloquent\Builder` (Eloquent builder instead of database query builder). 

`QueryBuilder` actually extends `Illuminate\Database\Eloquent\Builder`, so you can also just typehint `QueryBuilder` in your callback and still use all Eloquent methods like `where`, scopes, etc...

Good luck and feel free to open a new issue if this is not working out :)
