### ISSUE TITLE
How can ignore the wrong filter prams ?

### ISSUE THREAD

**Issue by jeanali** [spatie/laravel-query-builder#515]
**New with this package**

I'm using custom query filter and have URL for filtering the data like this

http://example.test/posts?filter[name]=true

All things is good but once I try to change filter[name] to filter[anything] I got this error

 ` Requested filter(s) anything are not allowed. Allowed filter(s) `

How can check if it right do filter, failed show all posts like normal ?

**Comment by aliene-ctrl** [comment]
This is actually a really annoying feature of an otherwise great package.

Is it just me or does [`ensureAllFiltersExist`](https://github.com/spatie/laravel-query-builder/blob/2258ce2d1accb5a286c9fef2bcf58398f1889dde/src/Concerns/FiltersQuery.php#L63) take it's concern a little too seriously? Is the exception really necessary? Is this method even necessary?

**Comment by dominikb** [comment]
I think the exception does exactly what it is supposed to do: it let's you react to an invalid query by generating a meaningful error response. This is quite helpful if you do not control the consumer of your API.

@jeanali : what you were asking for could be solved like this

```php
try {
    $models = QueryBuilder::for(MyModel::class)->allowedFilters('name');
} catch (InvalidFilterQuery $exception) {
    // Maybe log this or extend the response to provide information about this fallback-behaviour to your API consumer
   $models = MyModel::all();
}
```

**Comment by AlexVanderbist** [comment]
Hi! v3.3.0 adds a new config option to disable this exception. I've also opened a discussion for making the exception behave a bit better in a real world scenario here: #537 

Thanks for your concern and time!
