### ISSUE TITLE
whereJsonContains is not working

### ISSUE THREAD

**Issue by doraemonxxx** [spatie/laravel-query-builder#919]
whereJsonContains is not working even though you debug it and make it raw sql using  `toSql()` method

**Comment by djamesfar** [comment]
I have this problem as well.
Using laravel-query-builder v5, Laravel 11
Here's my AllowedFilters:
```$rmas = QueryBuilder::for(Rma::class)
            ->allowedFilters([
                AllowedFilter::partial('customer', 'contact_name'),
                AllowedFilter::exact('number', 'id'),
                AllowedFilter::exact('status', 'rma_status_id'),
                AllowedFilter::callback('part', function(\Illuminate\Database\Eloquent\Builder $query, $value) {
                    $query->whereHas('details', function($q) use ($value) {
                        $q->where('part_id', $value);
                    });
                }),
                AllowedFilter::callback('serial_number', function(\Illuminate\Database\Eloquent\Builder $query, $value) {
                    $query->whereHas('details', function($q) use ($value) {
                        $q->whereJsonContains('serial_numbers', $value);
                    });
                }),
            ])
```

The problem is the last filter, 'serial_number' callback function.  It is supposed to return all RMAs that contain RMA details (Rma 'details' relation) whose 'serial_numbers' json array contains the supplied serial_number ($value).
RmaDetail model casts 'serial_numbers' as array.

This works fine in tinker:
```$sn = 'MN220518063'
= "MN220518063"

> $rmas = Rma::whereHas('details', function($q) use ($sn) { $q->whereJsonContains('serial_numbers', $sn); })->get()
 ```
In tinker, this correctly returns the RMA record that contains an RmaDetail with serial_numbers json field that contains the supplied serial number.

Anything I'm doing wrong here?
