### ISSUE TITLE
Usage with Lumen: request()->fields() method is undefined

### ISSUE THREAD

**Issue by JessJNielsen** [spatie/laravel-query-builder#98]
I cannot get the `request()->fields()` method used in QueryBuilder.php to work. It appears to be a method instead of a magic field call.

When calling `request()->fields` it works as expected.

I am using Lumen 5.6 and also tested this functionality in a laravel 5.6 installation, with same results.

I use the newest release, 1.10.

**Comment by mdcass** [comment]
I'm seeing similar in a fresh Laravel 5.6 installation

```php
class UsersController extends Controller {
  public function index(ListUserRequest $request)
  {
    $users = QueryBuilder::for(User::class)
      ->defaultSort('-id')
      ->allowedIncludes(config('thc-core.query-builder.users.index.includes'))
      ->allowedFilters(config('thc-core.query-builder.users.index.filters'));

    return UserResource::collection($users->paginate());
  }
}
```

```log
[2018-09-12 10:41:38] testing.ERROR: Method Illuminate\Http\Request::fields does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Http\\Request::fields does not exist. at /home/vagrant/code/packages/thc/laravel-core-package/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:99)
[stacktrace]
#0 /home/vagrant/code/packages/thc/laravel-core-package/vendor/spatie/laravel-query-builder/src/QueryBuilder.php(176): Illuminate\\Http\\Request->__call('fields', Array)
#1 /home/vagrant/code/packages/thc/laravel-core-package/vendor/spatie/laravel-query-builder/src/QueryBuilder.php(47): Spatie\\QueryBuilder\\QueryBuilder->parseSelectedFields()
#2 /home/vagrant/code/packages/thc/laravel-core-package/vendor/spatie/laravel-query-builder/src/QueryBuilder.php(90): Spatie\\QueryBuilder\\QueryBuilder->__construct(Object(Sofa\\Eloquence\\Builder), Object(Illuminate\\Http\\Request))
#3 /home/vagrant/code/packages/thc/laravel-core-package/src/Http/Controllers/UsersController.php(41): Spatie\\QueryBuilder\\QueryBuilder::for(Object(Sofa\\Eloquence\\Builder))
#4 [internal function]: THC\\Core\\Http\\Controllers\\UsersController->index(Object(THC\\Core\\Http\\Requests\\ListUserRequest))
```

Although inconsistent with another installation of Laravel 5.6 and this package (with `composer update`d). Will explore more

**Comment by JessJNielsen** [comment]
I made a fork that changed the usage to collection objects rather than undocumented "magic" functionality: https://github.com/JessJNielsen/laravel-query-builder

I think for now it will do.
I must have forgotten to include the service provider.

**Comment by SamDevBR** [comment]
The solution provided by @JessJNielsen works for me with Lumen 5.6, great fork bro, thanks, but with Lumen I needed to create a helper function `request`, because the class `QueryBuilder` calls many times the request helper, and Lumen does not provide the helper called `request` to get an instance of the request, to do so I created the helper, would be very nice of you to fix your fork and create a PR, then this package will be 100% compatible with Lumen 5.6.

**Comment by AlexVanderbist** [comment]
The fixes in @JessJNielsen's repository look like a pretty good fix. I would merge a PR for this if anyone's up for it.

**Comment by SamDevBR** [comment]
@AlexVanderbist actually I was successful using this package in lumen without the fork, I just had to create two helpers (request, config_path) and publish the service provider and the config file, maybe remove these helper dependicies and create functions to do same would be great, the only thing left to do to use this with Lumen would be create the vendor:publish command, because lumen doesn't have it.

**Comment by AlexVanderbist** [comment]
Alright, that's good news! We don't use Lumen ourselves but again, I would happily merge a PR that adds this :)
